"""
MCP tool for generating onboarding guides from repository analysis.
"""

from .fetch_repo import fetch_repo_tool
from ..storage.context_store import ContextStore
from ..utils.validators import validate_repo_url, parse_github_url

# Try to import watsonx summarizer, but don't fail if not configured
try:
    from ..watsonx.summarizer import summarize_context
    WATSONX_AVAILABLE = True
except Exception:
    WATSONX_AVAILABLE = False


async def generate_guide_tool(repo_url: str, include_diagrams: bool = True) -> dict:
    """
    Generate a comprehensive onboarding guide for a repository.
    
    This tool:
    1. Validates the repository URL
    2. Checks if repo is cached (fetches if not)
    3. Gets context string and tech stack from cache
    4. Generates a structured markdown guide with predefined sections
    5. Optionally includes Mermaid diagrams
    
    Args:
        repo_url: GitHub repository URL
        include_diagrams: Whether to include architecture diagrams (default: True)
    
    Returns:
        Dictionary with the generated guide and metadata
    """
    try:
        # Validate URL
        is_valid, error_msg = validate_repo_url(repo_url)
        if not is_valid:
            return {
                "success": False,
                "error": error_msg
            }
        
        # Extract repo_key
        owner, repo_name = parse_github_url(repo_url)
        repo_key = f"{owner}/{repo_name}"
        
        # Check if repo is in cache
        store = ContextStore()
        cached_data = store.get(repo_key)
        
        if not cached_data:
            # Fetch repo first
            fetch_result = await fetch_repo_tool(repo_url)
            if not fetch_result.get("success"):
                return {
                    "success": False,
                    "error": f"Failed to fetch repository: {fetch_result.get('error', 'Unknown error')}"
                }
            # Get cached data after fetch
            cached_data = store.get(repo_key)
        
        # Get context string and tech stack
        context_string = store.get_context_string(repo_key)
        tech_stack = cached_data["tech_stack"]
        
        if not context_string:
            return {
                "success": False,
                "error": "No repository context available"
            }
        
        # Check if context is very large (over 40,000 chars)
        effective_context = context_string
        used_watsonx = False
        
        if len(context_string) > 40000 and WATSONX_AVAILABLE:
            try:
                effective_context = await summarize_context(context_string)
                used_watsonx = True
            except Exception:
                # Silently fall back to original context if summarization fails
                pass
        
        # TODO: Implement actual LLM prompt for guide generation
        # For now, return a placeholder
        guide_markdown = f"""# {repo_name} - Developer Onboarding Guide

## Project Overview
TODO: Generate project overview using LLM with context

## Tech Stack
**Primary Language:** {tech_stack.get('primary_language', 'Unknown')}

**All Languages:** {', '.join(tech_stack.get('all_languages', []))}

**Frameworks:**
{_format_frameworks(tech_stack.get('frameworks', {}))}

**Dependencies:**
{_format_dependencies(tech_stack.get('dependencies', {}))}

## Architecture
TODO: Generate architecture description using LLM with context
{_generate_architecture_diagram() if include_diagrams else ''}

## Key Modules
TODO: Generate key modules description using LLM with context

## Getting Started
TODO: Generate getting started instructions using LLM with context

## Entry Points
TODO: Generate entry points description using LLM with context

## First Week Tasks
TODO: Generate first week tasks using LLM with context

## Glossary
TODO: Generate glossary using LLM with context

---
*Generated by CodeOnboard MCP Server*
*Repository: {repo_url}*
*Total Files Analyzed: {tech_stack.get('total_files', 0)}*
*Has Tests: {'Yes' if tech_stack.get('has_tests') else 'No'}*
*Has Docker: {'Yes' if tech_stack.get('has_docker') else 'No'}*
*Has CI/CD: {'Yes' if tech_stack.get('has_ci') else 'No'}*
*Architecture: {tech_stack.get('architecture', 'standard').title()}*
"""
        
        sections = [
            "Project Overview",
            "Tech Stack",
            "Architecture",
            "Key Modules",
            "Getting Started",
            "Entry Points",
            "First Week Tasks",
            "Glossary"
        ]
        
        return {
            "success": True,
            "repo_key": repo_key,
            "guide_markdown": guide_markdown,
            "sections": sections,
            "tech_stack": tech_stack,
            "used_watsonx": used_watsonx,
            "message": f"Guide generated successfully{' (using WatsonX summarizer for large context)' if used_watsonx else ''}"
        }
    
    except Exception as e:
        return {
            "success": False,
            "error": f"Failed to generate guide: {str(e)}"
        }


def _format_frameworks(frameworks: dict) -> str:
    """Format frameworks dict as markdown list."""
    if not frameworks:
        return "None detected"
    
    result = []
    for category, items in frameworks.items():
        if items:
            result.append(f"- **{category.replace('_', ' ').title()}:** {', '.join(items)}")
    
    return "\n".join(result) if result else "None detected"


def _format_dependencies(dependencies: dict) -> str:
    """Format dependencies dict as markdown list."""
    if not dependencies:
        return "None detected"
    
    result = []
    for file_name, deps in dependencies.items():
        if deps:
            result.append(f"- **{file_name}:** {len(deps)} dependencies")
    
    return "\n".join(result) if result else "None detected"


def _generate_architecture_diagram() -> str:
    """Generate a placeholder for architecture diagram."""
    return """
### Architecture Diagram
```mermaid
graph TD
    A[TODO: Generate architecture diagram]
    B[Using Mermaid syntax]
    A --> B
```
"""

# Made with Bob
